name: 'Auto update'

on:
  watch:
    types: [started]

jobs:
  try_update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      uses: WingsZeng/go-auto-deps-action@v1
      with:
        repo_owner: 'twpayne'
        repo_name: 'chezmoi'
